project:
  type: book
  output-dir: docs
  resources:
    - fonts/

lang: en

filters:
  - tikz

tikz:
  svg-engine: pdftocairo

babelquarto:
  languagelinks: sidebar
  languagecodes:
    - name: en
      text: ":English"
    - name: he
      text: ":עברית"
  mainlanguage: en
  languages: [he]

title-he: "אֵיפָה וְאֵיפָה"
subtitle-he: "ממדים, יחידות וסדרי גודל"
author-he: "Yair Mau"

book:
  title: "Measure for Measure"
  subtitle: "Dimensions, units, and orders of magnitude"
  site-url: https://yairmau.github.io/units/
  author: "Yair Mau"
  repo-url: https://github.com/yairmau/units/
  favicon: archive/logo.png

  chapters:
    - index.en.qmd
    - part: mathematical foundations
      part-he: יסודות מתמטיים
      chapters:
        - mathematical_foundations/powers_rules.en.qmd
    - part: quantifying the world
      part-he: לכמת את העולם
      chapters:
        - quantifying/dimensions.en.qmd
        - quantifying/units.en.qmd
    - part: basic concepts
      part-he: מושגי יסוד
      chapters:
        - basic_concepts/area-and-volume.en.qmd
        - basic_concepts/concentration.en.qmd
        - basic_concepts/density.en.qmd

  sidebar:
    collapse-level: 2
    tools:
      - icon: house-fill
        href: https://yairmau.com/
    logo: archive/logo.png
  search: true

# bibliography: references.bib

format:
  html:
    css:
      - hebrew.css
      - styles.css
    theme:
    - flatly
    - custom.scss
    # - font_defs.css
    fontsize: 1.2em
    highlight-style: kate-custom.theme #kate #solarized # kate # tango # breeze # ayu # monokai # breezedark # espresso
    include-in-header:
      - includes.html
    code-line-numbers: true
    code-tools:
      source: repo  # https://quarto.org/docs/output-formats/html-code.html#code-tools
    callout-icon: false
    fig-align: center
    # the default MathJax rendering option yields ugly results, use katex
    html-math-method: katex

  pdf:
    documentclass: scrreprt
    include-in-header:
      - latex_preamble.tex
