---
dir: rtl
---

# מושגי יסוד

## שטח ונפח

לשטח יש ממד של אורך בריבוע, ולנפח יש ממד של אורך בחזקה שלוש.

**שימו לב!**  
בהמרת יחידות של שטח או נפח, אל תשכחו להעלות גם את גורם ההמרה בריבוע או בחזקה שלוש. למה הכוונה?  
הנה דוגמה.

::: {.card-info}
כמה מטרים רבועים יש בקילומטר רבוע?
:::

$$
1\, \mathrm{km}^2 = 1 \left( 10^3 \mathrm{m} \right)^2 = 1 \left( 10^3 \right)^2 \left(\mathrm{m} \right)^2 = 10^6\, \mathrm{m}^2
$$

בקילומטר רבוע יש מיליון מטרים רבועים.

### ליטר {.unnumbered}

ליטר אחד הוא הנפח של קובייה שאורך צלעה $10\,\mathrm{cm}$.

::: {.card-info}
כמה ליטרים יש במטר מעוקב?
:::

$$
1\, \mathrm{m}^3 = (100\, \mathrm{cm})^3 = \left(10 \cdot 10\, \mathrm{cm}\right)^3 = 10^3\left(10\, \mathrm{cm}\right)^3 = 10^3\, \mathrm{L}
$$

במטר מעוקב יש אלף ליטרים.

## ריכוזים וצפיפויות

ריכוזים וצפיפויות עונים למעשה על השאלה:

::: {.card-info}
כמה מחומר מסוים יש בנפח נתון?
:::

נפרט מעט.

### ריכוז {.unnumbered}

ריכוזים נפוצים מאוד בכימיה. הכמויות יכולות להימדד במולים, בגרמים, במיליגרמים וכדומה. הנפחים יכולים להימדד בליטרים, במיליליטרים וכדומה. כמה דוגמאות:

* ריכוז של חומר תרופתי מסוים: $2\,\mu\mathrm{g}/\mathrm{mL}$
* ריכוז של מגיב: $0.5\,\mathrm{mol}/\mathrm{L}$

### צפיפות {.unnumbered}

יש כמה סוגים של צפיפות, אך בדרך כלל הכוונה היא לצפיפות מסה:

::: {.card-info}
כמה מסה יש בנפח נתון?
:::

למשל, צפיפות הברזל היא $7.87\,\mathrm{g}/\mathrm{cm}^{3}$.

::: {.card-info}
מהי צפיפות הברזל ביחידות של $\mathrm{kg}/\mathrm{m}^{3}$?
:::


\begin{align}
&7.87\, &&\mathrm{g}&&\mathrm{cm}^{-3} \\
&7.87\, &&\left(10^{-3}10^3\,\mathrm{g}\right) &&(10^{-2}\,\mathrm{m})^{-3}\\
&7.87\, &&\left(10^{-3}\,\mathrm{kg}\right) &&(10^{-2})^{-3}\, (\mathrm{m})^{-3}\\
&7.87\, &&10^{-3}\, \mathrm{kg} &&10^{6}\, \mathrm{m}^{-3}\\
&7.87\cdot10^{-3}10^{6} &&\mathrm{kg} &&\mathrm{m}^{-3}\\
&7.87\cdot10^{3} &&\mathrm{kg} &&\mathrm{m}^{-3}\\
\end{align}

במטר מעוקב של ברזל יש $7870\,\mathrm{kg}$.

ודאו שאתם מבינים מה קורה בכל אחת מהמשוואות שלמעלה.
