# dimensions and units

## definition

**Dimensions** answer the question: what is being measured?
For example, we can measure length, mass or time.

**Units** answer: how to we measure? Length, for example, can be measured in centimeters, miles, or cubits (from your elbow to the tip of your middle finger).

The three fundamental dimensions in Classical Mechanics are **length**, **time**, and **mass**.

| Dimension         | Symbol | Description                  | SI Unit          |
|-------------------|--------|------------------------------|------------------|
| Length            | L      | distance or size             | meter (m)        |
| Time              | T      | duration or interval         | second (s)       |
| Mass              | M      | amount of matter             | kilogram (kg)    |


In addition to these, other important dimensions include **temperature**, **electric current**, and **amount of substance**.

::: {#offcanvasOtherDimensions .offcanvas .offcanvas-start}
::: {.offcanvas-header}
### Other dimensions {.unnumbered .unlisted}
<button type="button" class="btn-close" data-bs-dismiss="offcanvas"></button>
:::
::: {.offcanvas-body}
| Dimension         | Symbol | Description                  | SI Unit          |
|-------------------|--------|------------------------------|------------------|
| Temperature       | Θ      | degree of hotness            | kelvin (K)       |
| Electric current  | I      | flow of electric charge      | ampere (A)       |
| Amount of substance | N    | quantity of entities         | mole (mol)       |
| Luminous intensity | J     | brightness                   | candela (cd)     |
:::
:::

::: {.btn .btn-warning data-bs-toggle="offcanvas" data-bs-target="#offcanvasOtherDimensions" style="height: 2.5rem; line-height: 2.3rem; padding-top: 0; padding-bottom: 0;"}
See here.
:::

## derived quantities

We can combine the three fundamental dimensions most used in classical mechanics to derive many familiar concepts.

| Quantity         | Derived dimensions | SI Unit          |
|-------------------|--------|------------------------------|
| Velocity            | L T$^{-1}$     | meter per second (m/s)        |
| Area              | L$^2$      | meter squared (m$^2$)       |
| Force              | MLT$^{-2}$      | newton (N)    |
| Frequency          | T$^{-1}$  | hertz (Hz)  |
| And many many more... |  |  |