---
dir: rtl
---

# ממדים ויחידות

## הגדרה

**ממדים** עונים על השאלה: מה נמדוד?
למשל, אפשר למדוד אורך, מסה או זמן.

**יחידות** עונות על השאלה: איך מודדים? אורך, למשל, אפשר למדוד בסנטימטרים, מילים או באמות (מהמרפק ועד קצה האצבע האמצעית).

שלושת הממדים היסודיים במכניקה הקלאסית הם **אורך**, **זמן** ו**מסה**.

| ממד | סמל | תיאור | יחידת SI |
|------|------|-------|----------|
| אורך | L | מרחק או גודל | מטר (m) |
| זמן | T | משך או מרווח זמן | שנייה (s) |
| מסה | M | כמות החומר | קילוגרם (kg) |

בנוסף עליהם, ממדים חשובים אחרים כוללים **טמפרטורה**, **זרם חשמלי** ו**כמות חומר**.

::: {#offcanvasOtherDimensions .offcanvas .offcanvas-start}
::: {.offcanvas-header}
### ממדים אחרים {.unnumbered .unlisted}
<button type="button" class="btn-close" data-bs-dismiss="offcanvas"></button>
:::
::: {.offcanvas-body}
| ממד | סמל | תיאור | יחידת SI |
|------|------|-------|----------|
| טמפרטורה | Θ | דרגת חום | קלווין (K) |
| זרם חשמלי | I | זרימת מטען חשמלי | אמפר (A) |
| כמות חומר | N | מספר היסודות | מול (mol) |
| עצמת אור | J | בהירות | קנדלה (cd) |
:::
:::

::: {.btn .btn-warning data-bs-toggle="offcanvas" data-bs-target="#offcanvasOtherDimensions" style="height: 2.5rem; line-height: 2.3rem; padding-top: 0; padding-bottom: 0;"}
ראו כאן.
:::

## כמויות נגזרות

אפשר לשלב את שלושת הממדים היסודיים הנפוצים ביותר במכניקה הקלאסית כדי לקבל מושגים מוכרים רבים.

| כמות | ממדים נגזרים | יחידת SI |
|------|---------------|----------|
| מהירות | <span dir="ltr">LT$^{-1}$</span> | מטר לשנייה (m/s) |
| שטח | <span dir="ltr">L$^2$</span> | מטר בריבוע (m$^2$) |
| כוח | <span dir="ltr">M L T$^{-2}$</span> | ניוטון (N) |
| תדר | <span dir="ltr">T$^{-1}$</span> | הרץ (Hz) |
| ועוד ועוד... |  |  |